#
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://mysql-standalone/spandan?allowPublicKeyRetrieval=true&useSSL=false
#    username: root
#    password: Manumanohar@74
#    hikari:
#      initialization-fail-timeout: 0
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: create